export type AssumptionTag =
  | 'GRAMS_ASSUMED'
  | 'MULTIPLIER_APPLIED'
  | 'SOURCE_BLS'
  | 'SOURCE_OFF'
  | 'SOURCE_USDA'
  | 'SOURCE_MOCK'
  | 'CANONICAL_SHORTCUT_USED'
  | 'ML_WITHOUT_DENSITY'
  | 'INGREDIENT_EDIT_UNSUPPORTED';
