import { PortionHint } from './PortionHint';

export const SEED_PORTION_HINTS: PortionHint[] = [
  {
    foodIdentityKey: 'canonical:egg',
    unit: 'piece',
    gramsPerUnit: 60,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
  {
    foodIdentityKey: 'canonical:banana',
    unit: 'piece',
    gramsPerUnit: 120,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
  {
    foodIdentityKey: 'canonical:apple',
    unit: 'piece',
    gramsPerUnit: 180,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
  {
    foodIdentityKey: 'canonical:carrot',
    unit: 'piece',
    gramsPerUnit: 60,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
  {
    foodIdentityKey: 'canonical:potato',
    unit: 'piece',
    gramsPerUnit: 150,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
  {
    foodIdentityKey: 'canonical:toast',
    unit: 'slice',
    gramsPerUnit: 35,
    source: 'seed',
    visibility: 'global_candidate',
    reviewStatus: 'none',
    confidence: 0.75,
    evidenceCount: 1,
  },
];
